name: Python package 
on: [push] 
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4 
        with:
          python-version: "3.9"
      - name: Install packages 
        run: pip install -r requirements.txt
      - name: Run tests 
      # ici github.sha est le dernier bon commit du push 
      # ici git log -1 --pretty=format:'%H' HEAD^ est le dernier commit avant le push
        run: python myscript.py
